TOP = ..
include $(TOP)/configure/CONFIG

cp --force EXAMPLE_commonPlugin_settings.req $(INSTALL_LOCATION)/iocBoot/commonPlugin_settings.req
cp --force EXAMPLE_commonPlugins.cmd $(INSTALL_LOCATION)/iocBoot/commonPlugins.cmd

include $(TOP)/configure/RULES_DIRS
